// mobile/android/settings.gradle.kts
//
// PR-28 (Sprint 5) — first committed Gradle config for the OpenE2EE Android app.
//
// Closes the gap left by Sprint 3 §10 ("Android Gradle scaffolding deferred")
// and Sprint 4 PR-24 ("move vpn_service_android.kt into the Android source
// tree"). The earlier PRs relocated the Kotlin sources and validated the
// package/import/manifest chain, but did not commit the actual Gradle build
// files. With this commit, `./gradlew assembleDebug` is now runnable from a
// clean clone of the repo (subject to the developer's `local.properties`
// pointing at the Flutter SDK + Android SDK; see `local.properties.example`).
//
// Layout:
//
//   settings.gradle.kts      — root settings; declares project includes,
//                              pluginManagement, dependencyResolutionManagement
//   build.gradle.kts         — root project config (subprojects' plugin
//                              versions via the plugins {} block)
//   app/build.gradle.kts     — Flutter module config; applies the Flutter +
//                              Kotlin Android plugins, declares app id,
//                              minSdk/targetSdk/compileSdk, signing config,
//                              runtime dependencies (kotlinx-coroutines,
//                              AndroidX core), and the vpn service path.
//   gradle/wrapper/          — Gradle wrapper bootstrap (version + URL).
//                              The actual `gradle-wrapper.jar` binary is
//                              generated by `gradle wrapper` and remains
//                              gitignored (see .gitignore).
//   gradlew, gradlew.bat     — wrapper launchers (generated by
//                              `gradle wrapper`; committed for reproducibility).
//
// Plugin / Gradle versions:
//
//   - AGP (Android Gradle Plugin) — 8.1.x, matches Flutter 3.16+ defaults
//     and is compatible with compileSdk = 34.
//   - Kotlin Android plugin — 1.9.22 (the same line used by the Flutter
//     Android embedding for Dart-side plugins).
//   - Gradle wrapper — 8.4, aligned with AGP 8.1.x compatibility matrix.
//
// References:
//   - https://docs.flutter.dev/deployment/android
//   - https://developer.android.com/build/releases/gradle-plugin
//   - docs/SPRINT-3-SCOPE.md §10
//   - docs/SPRINT-5-SCOPE.md §PR-28

pluginManagement {
    val flutterSdkPath = run {
        val properties = java.util.Properties()
        file("local.properties").inputStream().use { properties.load(it) }
        val flutterSdkPath = properties.getProperty("flutter.sdk")
        require(flutterSdkPath != null) {
            "flutter.sdk not set in local.properties — copy local.properties.example"
        }
        flutterSdkPath
    }

    includeBuild("$flutterSdkPath/packages/flutter_tools/gradle")

    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }

    plugins {
        // Flutter's own Android Gradle plugin — applied in app/build.gradle.kts.
        id("dev.flutter.flutter-plugin-loader") version "1.0.0" apply false
    }
}

// Single-module repo for now; Flutter module lives at `app/`.
include(":app")