// SPDX-License-Identifier: MIT
//
// tool/ci_grep_privacy_violations.dart
//
// Sprint 7 / Item 12 — STRIDE-3-01: CI guard for IMEI / TelephonyManager
// re-introduction (F1 anonimlik, ADR-0006 §"Veri Minimizasyonu").
//
// Why a Dart script and not bash grep:
//   * Mobile lib/test code is Dart — Dart-level identifiers need to be
//     matched against Dart lexical rules (word boundaries, no false
//     positives inside string literals or comments).
//   * The existing privacy-invariant test
//     `mobile/test/shared/device_identity_test.dart` (lines 245-249)
//     documents the policy via `RegExp(r'...imei...')` and explicitly
//     says "Free-form mentions in comments / doc strings are allowed
//     (and necessary) to document the contract." A naive `grep -rnE
//     'imei'` would block the documentation that enforces the policy.
//   * Bash `grep` doesn't have a Dart-aware scanner; doing the
//     strip-and-match in Dart keeps the guard auditable in the same
//     language as the code it guards.
//
// What it does:
//   1. Walks each supplied root recursively.
//   2. For each source file (.dart, .kt, .java, .swift, .m, .h, .gradle,
//      .kts, .cs, .cpp, .cc, .hpp, .c):
//        a. Strips block comments `/* ... */` (preserving newlines so
//           line numbers stay accurate).
//        b. Strips line comments `// ...`.
//        c. Strips Dart raw / triple / plain / template string
//           literal bodies — keeping `${...}` interpolations visible
//           because they are real expressions.
//        d. Applies a case-insensitive word-boundary regex for the
//           forbidden identifiers.
//   3. Prints every match as `path:line:col: <identifier>` and exits
//      non-zero if ANY match survived.
//
// Exit codes:
//   0  — clean, no forbidden identifier usage in code position
//   1  — one or more matches found (CI gate fails)
//   2  — usage / IO error
//
// Usage:
//   dart run tool/ci_grep_privacy_violations.dart
//   dart run tool/ci_grep_privacy_violations.dart --roots mobile/lib mobile/test
//   dart run tool/ci_grep_privacy_violations.dart --help
//
// Hand-off origin: cyber-security review of PR-39 mobile security
// hardening (Sprint 6 / ADR-0006 §"Veri Minimizasyonu"). Re-introducing
// `TelephonyManager`, `getDeviceId`, IMEI / ANDROID_ID reads, or the
// `device_info` plugin would re-open the F1 anonimlik regression
// closed by PR-15.

import 'dart:io';

/// Patterns that, when found in *code position* (i.e. outside
/// comments and string literals), indicate forbidden hardware-id
/// usage under ADR-0006 / F1 anonimlik.
///
/// - `imei` — Android `TelephonyManager.getImei()` return value, any
///   field / getter / variable named after the IMEI.
/// - `telephonymanager` — Android class; touching it from a privacy
///   posture is forbidden per ADR-0006 line 74.
/// - `getdeviceid` — generic device-id read; covers both Dart-side
///   `package:device_info` returns and any future native bridge.
/// - `androidid` — `Settings.Secure.ANDROID_ID` reads; same threat
///   class as IMEI for cross-device re-identification.
///
/// All matched case-insensitively as whole words.
const _forbiddenPattern = r'\b(?:imei|telephonymanager|getdeviceid|androidid)\b';

/// Source-file extensions the guard scans. Tests, configs, and
/// generated files are excluded on purpose — the contract applies to
/// hand-written code, not to manifest generators or pubspec.lock.
const _scannedExtensions = <String>{
  '.dart',
  '.kt',
  '.kts',
  '.java',
  '.swift',
  '.m',
  '.h',
  '.cpp',
  '.cc',
  '.cxx',
  '.hpp',
  '.hxx',
  '.c',
  '.cs',
  '.gradle',
};

/// Default roots per Sprint 7 / Item 12 scope. The script accepts
/// overrides via `--roots` so the same script can later guard the
/// native Android (`mobile/android/app/src/main/kotlin/...`) and iOS
/// (`mobile/ios/...`) trees without re-inventing the scanner.
const _defaultRoots = <String>['mobile/lib', 'mobile/test'];

/// Files we never scan even when their extension would otherwise
/// match — typically generated / vendored content where matches are
/// either out of our control (Flutter plugin registrant) or pinned to
/// upstream (`Generated.xcconfig`).
const _skipPathFragments = <String>[
  // Android plugin registrant is regenerated by Flutter tooling.
  'GeneratedPluginRegistrant',
  // iOS generated xcconfigs / Pods are managed by CocoaPods.
  'Pods/',
  '.dart_tool/',
  'build/',
  '.symlinks/',
];

void main(List<String> args) {
  final parsed = _parseArgs(args);
  if (parsed.showHelp) {
    _printUsage();
    exit(0);
  }

  final roots = parsed.roots;
  if (roots.isEmpty) {
    stderr.writeln('error: no roots to scan (use --roots or pass dir args)');
    _printUsage();
    exit(2);
  }

  final files = <File>[];
  for (final root in roots) {
    final entity = FileSystemEntity.typeSync(root);
    if (entity == FileSystemEntityType.notFound) {
      stderr.writeln('error: root does not exist: $root');
      exit(2);
    }
    _collect(root, files);
  }

  if (files.isEmpty) {
    stderr.writeln('error: no source files found under: ${roots.join(", ")}');
    exit(2);
  }

  final regex = RegExp(_forbiddenPattern, caseSensitive: false);
  var totalMatches = 0;
  final perFile = <String>[];

  for (final file in files) {
    final path = file.path.replaceAll('\\', '/');
    final src = file.readAsStringSync();
    final stripped = _stripCommentsAndStrings(src);
    for (final match in regex.allMatches(stripped)) {
      totalMatches++;
      final line = _lineNumber(stripped, match.start);
      final col = _columnNumber(stripped, match.start);
      final snippet = src.substring(_lineStart(src, line), _lineEnd(src, line)).trim();
      perFile.add('  $path:$line:$col  ${match.group(0)}   | $snippet');
    }
  }

  if (totalMatches == 0) {
    stdout.writeln(
        '[ci_grep_privacy_violations] OK — scanned ${files.length} files under ${roots.join(", ")}; '
        'no IMEI / TelephonyManager / getDeviceId / androidId usage detected.');
    exit(0);
  }

  stdout.writeln(
      'F1 anonimlik guard: IMEI/TelephonyManager usage detected — see ADR-0006');
  stdout.writeln('Scanned roots: ${roots.join(", ")} (${files.length} files)');
  stdout.writeln('Forbidden identifier hits: $totalMatches');
  stdout.writeln('Matches:');
  for (final line in perFile) {
    stdout.writeln(line);
  }
  exit(1);
}

/// Strip block comments, line comments, and string-literal bodies,
/// preserving newlines so the line/column math stays aligned with
/// the source on disk.
///
/// The scanner is a small state machine over the original source —
/// simpler than pulling in `package:analyzer`, and it matches the
/// shape of every Dart / Kotlin / Java / Swift file in the repo.
String _stripCommentsAndStrings(String src) {
  final out = StringBuffer();
  var i = 0;
  final n = src.length;

  // Stack of "are we currently inside a string" contexts.
  // null = not in any string
  // '\'', '"' = inside that single-quote string (Dart/Kotlin/Swift)
  // '"""' / "'''" = inside triple-quoted (Dart only; Kotlin/Swift don't have them)
  // 'r' = raw string prefix seen, just consumed
  String? stringDelim;
  var rawString = false;

  while (i < n) {
    final c = src[i];
    final next = i + 1 < n ? src[i + 1] : '';

    // Block comment: /* ... */
    if (stringDelim == null && c == '/' && next == '*') {
      var j = i + 2;
      while (j < n - 1 && !(src[j] == '*' && src[j + 1] == '/')) {
        // Preserve newlines so line numbers stay accurate.
        if (src[j] == '\n') {
          out.write('\n');
        }
        j++;
      }
      // Skip the closing */ if present; if unterminated, swallow to EOF.
      i = (j < n - 1) ? j + 2 : n;
      // Pad with a space so a comment that touches code doesn't
      // accidentally glue two identifiers together (rare in Dart
      // but cheap to be safe).
      out.write(' ');
      continue;
    }

    // Line comment: // ...
    if (stringDelim == null && c == '/' && next == '/') {
      var j = i + 2;
      while (j < n && src[j] != '\n') {
        j++;
      }
      i = j;
      out.write(' ');
      continue;
    }

    // Hash line comment: # ... (Kotlin / shell / Python; harmless in Dart)
    if (stringDelim == null && c == '#') {
      var j = i + 1;
      while (j < n && src[j] != '\n') {
        j++;
      }
      i = j;
      out.write(' ');
      continue;
    }

    // String-literal entry. We support:
    //   '...'        "..."           plain Dart/Kotlin/Swift strings
    //   '''..'''     """.."""        Dart triple-quoted strings
    //   r'..'        r".."           Dart raw strings
    //   $identifier  ${expression}   string interpolation (we KEEP the
    //                                expression so identifiers inside
    //                                `${...}` are still visible — a
    //                                developer who interpolates an IMEI
    //                                variable is a real violation).
    if (stringDelim == null && (c == '\'' || c == '"')) {
      // Detect triple-quoted.
      if (next == c && i + 2 < n && src[i + 2] == c) {
        stringDelim = c * 3;
        rawString = false;
        out.write('   ');
        i += 3;
        continue;
      }
      // Detect raw prefix on a Dart string ('r' or 'R' immediately
      // before the opening quote, with no whitespace).
      final precededByRaw =
          i > 0 && (src[i - 1] == 'r' || src[i - 1] == 'R');
      stringDelim = c;
      rawString = precededByRaw;
      out.write(' ');
      i += 1;
      continue;
    }

    // Inside a string — handle escapes, interpolation, and the close.
    if (stringDelim != null) {
      if (c == '\n' && stringDelim.length == 1) {
        // Unterminated single-line string at EOL — keep the
        // newline so line numbers stay aligned, then exit string.
        out.write('\n');
        stringDelim = null;
        rawString = false;
        i++;
        continue;
      }
      // Raw strings ignore backslash escapes (Dart spec: r'...' has
      // no escapes except \" / \' inside, but for our guard we only
      // care about the closing delimiter, so we treat raw as
      // "the next matching quote closes us").
      if (!rawString && c == '\\' && i + 1 < n) {
        // Preserve the escaped character (e.g. \" inside a string)
        // so any identifier-like contents don't accidentally line up
        // with code position. Also keep newlines aligned.
        if (src[i + 1] == '\n') {
          out.write('\n');
        } else {
          out.write('  ');
        }
        i += 2;
        continue;
      }
      // String interpolation: $ident or ${expr}. We KEEP the
      // expression body (anything between ${ and matching }) so that
      // identifiers inside it remain scannable. A literal '$' that
      // is not the start of interpolation is just a character.
      if (!rawString && c == '\$' && (next == '{' || _isIdentStart(next))) {
        if (next == '{') {
          // ${ ... } — find matching close brace, keep contents.
          out.write('\$ ');
          i += 2;
          var depth = 1;
          while (i < n && depth > 0) {
            final ch = src[i];
            if (ch == '{') {
              depth++;
              out.write(ch);
              i++;
            } else if (ch == '}') {
              depth--;
              if (depth == 0) {
                i++;
                break;
              }
              out.write(ch);
              i++;
            } else if (ch == '"' || ch == '\'') {
              // Embedded string inside interpolation — strip its body
              // by recursing one level.
              final innerDelim = ch;
              out.write(ch);
              i++;
              while (i < n && src[i] != innerDelim) {
                if (src[i] == '\\' && i + 1 < n) {
                  out.write('  ');
                  i += 2;
                } else if (src[i] == '\n') {
                  out.write('\n');
                  i++;
                } else {
                  out.write(' ');
                  i++;
                }
              }
              if (i < n) {
                out.write(src[i]); // closing quote
                i++;
              }
            } else {
              out.write(ch);
              i++;
            }
          }
          continue;
        } else {
          // $ident — keep the identifier so it's still scannable.
          // It is *interpolated* code; if it references an IMEI
          // variable we'd want to catch that anyway.
          out.write('\$');
          i++;
          while (i < n && _isIdentPart(src[i])) {
            out.write(src[i]);
            i++;
          }
          continue;
        }
      }
      // End of string?
      if (stringDelim.length == 3) {
        if (c == stringDelim[0] && next == stringDelim[0] &&
            i + 2 < n && src[i + 2] == stringDelim[0]) {
          out.write('   ');
          i += 3;
          stringDelim = null;
          rawString = false;
          continue;
        }
        out.write(' ');
        i++;
        continue;
      } else {
        if (c == stringDelim) {
          out.write(' ');
          i++;
          stringDelim = null;
          rawString = false;
          continue;
        }
        if (c == '\n') {
          out.write('\n');
        } else {
          out.write(' ');
        }
        i++;
        continue;
      }
    }

    // Plain code character — pass through.
    out.write(c);
    i++;
  }

  return out.toString();
}

bool _isIdentStart(String c) {
  if (c.isEmpty) return false;
  final code = c.codeUnitAt(0);
  // [A-Za-z_]
  return (code >= 0x41 && code <= 0x5A) ||
      (code >= 0x61 && code <= 0x7A) ||
      code == 0x5F;
}

bool _isIdentPart(String c) {
  if (c.isEmpty) return false;
  final code = c.codeUnitAt(0);
  // [A-Za-z0-9_]
  return (code >= 0x41 && code <= 0x5A) ||
      (code >= 0x61 && code <= 0x7A) ||
      (code >= 0x30 && code <= 0x39) ||
      code == 0x5F;
}

int _lineNumber(String s, int offset) {
  var line = 1;
  for (var i = 0; i < offset && i < s.length; i++) {
    if (s[i] == '\n') line++;
  }
  return line;
}

int _columnNumber(String s, int offset) {
  var col = 1;
  for (var i = offset - 1; i >= 0; i--) {
    if (s[i] == '\n') break;
    col++;
  }
  return col;
}

int _lineStart(String s, int line) {
  var current = 1;
  var i = 0;
  while (i < s.length && current < line) {
    if (s[i] == '\n') current++;
    i++;
  }
  return i;
}

int _lineEnd(String s, int line) {
  var current = 1;
  var i = 0;
  while (i < s.length) {
    if (s[i] == '\n') {
      if (current == line) return i;
      current++;
    }
    i++;
  }
  return s.length;
}

void _collect(String root, List<File> out) {
  final entity = FileSystemEntity.typeSync(root);
  if (entity == FileSystemEntityType.directory) {
    final dir = Directory(root);
    for (final child in dir.listSync(recursive: true, followLinks: false)) {
      if (child is! File) continue;
      final path = child.path.replaceAll('\\', '/');
      if (_skipPathFragments.any(path.contains)) continue;
      final ext = _extOf(path);
      if (_scannedExtensions.contains(ext)) {
        out.add(child);
      }
    }
  } else if (entity == FileSystemEntityType.file) {
    final f = File(root);
    final ext = _extOf(f.path);
    if (_scannedExtensions.contains(ext)) {
      out.add(f);
    }
  }
}

String _extOf(String path) {
  final slash = path.lastIndexOf('/');
  final base = slash >= 0 ? path.substring(slash + 1) : path;
  final dot = base.lastIndexOf('.');
  if (dot < 0) return '';
  return base.substring(dot);
}

class _Parsed {
  _Parsed({required this.roots, required this.showHelp});
  final List<String> roots;
  final bool showHelp;
}

_Parsed _parseArgs(List<String> args) {
  if (args.contains('-h') || args.contains('--help')) {
    return _Parsed(roots: const [], showHelp: true);
  }
  final roots = <String>[];
  var i = 0;
  while (i < args.length) {
    final a = args[i];
    if (a == '--roots') {
      i++;
      while (i < args.length && !args[i].startsWith('-')) {
        roots.add(args[i]);
        i++;
      }
    } else if (a.startsWith('--')) {
      stderr.writeln('error: unknown flag "$a"');
      _printUsage();
      exit(2);
    } else {
      roots.add(a);
      i++;
    }
  }
  if (roots.isEmpty) {
    roots.addAll(_defaultRoots);
  }
  return _Parsed(roots: roots, showHelp: false);
}

void _printUsage() {
  stdout.writeln(
      'tool/ci_grep_privacy_violations.dart — F1 anonimlik CI guard (Sprint 7 / Item 12)');
  stdout.writeln('');
  stdout.writeln('USAGE:');
  stdout.writeln('  dart run tool/ci_grep_privacy_violations.dart [options] [root ...]');
  stdout.writeln('');
  stdout.writeln('OPTIONS:');
  stdout.writeln('  --roots <dir ...>   One or more root directories to scan.');
  stdout.writeln('                      Defaults to: ${_defaultRoots.join(", ")}');
  stdout.writeln('  -h, --help          Show this help.');
  stdout.writeln('');
  stdout.writeln('EXIT CODES:');
  stdout.writeln('  0  clean (no forbidden identifier usage in code position)');
  stdout.writeln('  1  one or more forbidden identifiers detected');
  stdout.writeln('  2  usage / IO error');
  stdout.writeln('');
  stdout.writeln('Hand-off origin: cyber-security review of PR-39 (Sprint 6) —');
  stdout.writeln('the F1 anonimlik contract (ADR-0006 §Veri Minimizasyonu).');
}